name: Continuous Delivery

on:
  release:
    types: [ published ]
  schedule:
    - cron: '0 0 * * 0' # every sunday at midnight

jobs:

  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Get latest release tag
        id: latest_tag
        run: |
          echo ::set-output name=tag::$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
      - name: Log in to Docker Hub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          make release GOTENBERG_VERSION=${{ github.event.release.tag_name || steps.latest_tag.outputs.tag }}
          make release GOTENBERG_VERSION=${{ github.event.release.tag_name || steps.latest_tag.outputs.tag }} DOCKER_REPOSITORY=thecodingmachine
